### ISSUE TITLE
Rename to konn

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/konn#19]
#### What

- https://twitter.com/silentworks/status/1444411816835174400
- https://twitter.com/_philpl/status/1444365755244482567
- https://twitter.com/rohmanhm/status/1444948913010589698?s=20
- https://twitter.com/_wodin_/status/1444906977105219584?s=20

#### Why

If it is actively offending or confusing enough people then its a problem. Still gathering data.

#### How

- New name would need to be equally short and concise

#### TODO

- [x] rename repo
- [x] squat npm package
- [ ] publish new version to npm package
- [ ] update README
- [ ] update JSDoc if needed

**Comment by jasonkuhrt** [comment]
Maybe `konx`
